# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'IHKeyboardAvoiding'
  pod 'FloatingPanel'

  # Pods for Test-Demo
  
  target 'Test-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test-DemoUITests' do
    # Pods for testing
  end

end
